### ISSUE TITLE
Improve task reflection step to capture all attributes of a task

### ISSUE THREAD

**Issue by rajivsinclair** [room302studio/coachartie#105]
when the user mention a todo, Coach Artie should add a todo to the todolist (even if the user message does not use a specific syntax). see details in comments on related issue # 60 [here](https://github.com/room302studio/coachartie/issues/60#issue-2172434694)

**Comment by ejfox** [comment]
Closed in this commit https://github.com/room302studio/coachartie/commit/25736aa3d19aa392ef0b55918b01b9868128be91
