### ISSUE TITLE
Error processing message: Cannot read properties of undefined

### ISSUE THREAD

**Issue by rajivsinclair** [room302studio/coachartie#112]
api.js[2120462]: {"level":"error","message":"🚨 Error processing message: Cannot read properties of undefined (reading 'length')","service":"api"}![image](https://github.com/room302studio/coachartie/assets/4379424/b943616f-578c-411a-ac96-0689c6248708)

**Comment by rajivsinclair** [comment]
![Screenshot 2024-03-27 at 11 52 28 PM](https://github.com/room302studio/coachartie/assets/4379424/04841e01-273c-4f49-bc87-97ed5feae138)

**Comment by ejfox** [comment]
Stale and not enough information
