### ISSUE TITLE
when tachio retrieves memories tachio doesn't know whether the memory came from this conversation or a different conversation

### ISSUE THREAD

**Issue by rajivsinclair** [room302studio/coachartie#124]
When tachio is replying to a conversation in Missive, Tachio is currently recalling memories from all of their other conversations and Tachio is not able to distinguish between the memories that are directly relevant to this conversation vs memories that are from a different conversation. When asked follow-up questions, Tachio confidently asserts that these memories came from the current conversation even when they do not. This results in a confusing dialog and should be remedied. 

One solution would be to track which conversation(s) a specific memory is sourced from in the memories table using an array so that multiple conversations can be associated, e.g., in cases where a memory is sourced from multiple conversations or was generated by summarizing/reflecting on multiple ancestral memories which each came from a different conversation.

Currently the `memories` table already has a `conversation_id` column that @ejfox  created but it is completely blank.

**Comment by ejfox** [comment]
This is existing behavior of Coach Artie and requires a more thoughtful feature request and completion criteria, this has to do with the ratio of memories and the relevance search, and as long as the context is available to give the correct answer, much of this comes down to prompt engineering - happy to re-open an Issue with a more fully-architected feature request

**Comment by rajivsinclair** [comment]
When Tachio is retrieving memories, the metadata of each memory (including which conversations each memory is from) should be included. This may already be implemented in the existing retrieval process, but it can't be tested because all of the memories that have been formed so far are [lacking any specific conversation_id](https://github.com/room302studio/coachartie/issues/126). Can you confirm @ejfox if that's already included in the logic for the retrieval process and let us know when we should test again after [PR # 134](https://github.com/room302studio/coachartie/pull/134) is deployed?
