### ISSUE TITLE
When tachio creates memories, the memories should specify which conversation(s) they came from

### ISSUE THREAD

**Issue by rajivsinclair** [room302studio/coachartie#125]
The `conversation_id` field should be an array so that it can store one or more conversation IDs from Missive associated with the memory. If the memory has more than one relevant conversation_id, for example if it is the product of reflecting on multiple earlier memories, then the array can store multiple conversation IDs.

**Comment by ejfox** [comment]
It doesn't make much sense for me for conversation_id to be an array, I don't think there is any way of creating memories from multiple conversations

**Comment by rajivsinclair** [comment]
The reason I suggested this is because you had explained earlier that Coach Artie had already performed a "sleep-like" reflection process to combine multiple memories when you did the memories migration for Coach Artie a few months ago.

**Comment by rajivsinclair** [comment]
@ejfox the reason I suggested this is because you had explained earlier that Coach Artie had already performed a "sleep-like" reflection process to combine multiple memories when you did the memories migration for Coach Artie a few months ago.
