### ISSUE TITLE
tachio says that there is no deepdocumentingest capability

### ISSUE THREAD

**Issue by rajivsinclair** [room302studio/coachartie#127]
Instead of actually using the deepdocumentingest capability, tachio just invented some contents that are not in the linked document and then when I asked again tachio said that it doesn't have a deep document ingest capability.

![Screenshot 2024-03-27 at 11 46 28 PM](https://github.com/room302studio/coachartie/assets/4379424/e75fbb36-195a-49ee-80dd-13982e376d15)
![Screenshot 2024-03-27 at 11 48 08 PM](https://github.com/room302studio/coachartie/assets/4379424/93f2d6da-5134-4af9-8c57-8038ef462b5b)

**Comment by ejfox** [comment]
We have not updated Tachio to include our latest changes, including the new capability.
