### ISSUE TITLE
tachio is persistently failing to form any memories

### ISSUE THREAD

**Issue by rajivsinclair** [room302studio/coachartie#128]
All of the recent memories just say _"It seems there might have been a misunderstanding or a technical issue with your message, as it simply states "undefined." ..._
![Screenshot 2024-03-27 at 11 55 44 PM](https://github.com/room302studio/coachartie/assets/4379424/af0a855d-a006-4cd4-8569-b129d9450e14)
![Screenshot 2024-03-28 at 12 15 47 AM](https://github.com/room302studio/coachartie/assets/4379424/c0d1acb9-6923-4f4c-aa2b-89b4b7b8ec24)

**Comment by ejfox** [comment]
This is related to the error you introduced in this PR: https://github.com/room302studio/coachartie/pull/115/files#diff-1cbda34460db92d4ad755248356e01a93fa8afb3e78f3ae866547fddf34c163bR123

I fixed it here: https://github.com/room302studio/coachartie/pull/132

**Comment by rajivsinclair** [comment]
@ejfox it seems that these invalid memories began (Mar 22) a few days before that PR was merged into main (Mar 25), so there's another cause.

**Comment by rajivsinclair** [comment]
@ejfox these invalid memories are continuing to form as of today. These are the only memories being created in our memories table. Additionally, the conversation_id and related_message_id fields/columns are still entirely blank.
![Screenshot 2024-03-30 at 8 30 35 AM](https://github.com/room302studio/coachartie/assets/4379424/724dd62d-19cc-4c7f-8cbf-b5ae10194cf6)

**Comment by rajivsinclair** [comment]
This issue is not closed.
