### ISSUE TITLE
As PDW, I want the AI assistant to track all tasks in my organization and group them by project, so I can ask questions and receive answers informed by my organizational data

### ISSUE THREAD

**Issue by n0fray** [room302studio/coachartie#60]
- [ ] When user is chatting with Tachio, if a to-do item has been described that does not exist, a new item should be created
- [ ] This new task should be associated with the related project
- [ ] Project comes from the context of the conversational thread
- [ ] If conversation thread is not clear, and project association cannot be determined then Tachio should ask for clarification
- [ ] Tachio understands due date from conversational content
- [ ] If Tachio does not understand due date from conversational content, then should ask for clarification on due data
- [ ] If due date is given, should be connected to the associated task and scheduled accordingly

**Comment by n0fray** [comment]
@rajivsinclair please add proposed data structure and attributes here

**Comment by ejfox** [comment]
This is stale, we will not be adding all of these attributes to our todos table
