### ISSUE TITLE
Tachio’s prompt architecture should be stored/retrieved from the database (rather than the codebase)

### ISSUE THREAD

**Issue by n0fray** [room302studio/coachartie#71]
Tachio should read all prompts from the database, instead of from the prompt.js in the codebase. 

This way the prompts themselves are stored securely/isolated for Tachio and the prompts can be easily adjusted on-the-fly by PDW team members (or Tachio) simply writing/updating the prompts table in the database.

**Comment by ejfox** [comment]
prompts.js -> supabase `prompts` table
