### ISSUE TITLE
Weekly Briefing v0

### ISSUE THREAD

**Issue by curran** [room302studio/coachartie#91]
* Look at all memories from this week (timestamp comparison in memories table - leverage `remember.js`)
* Turn this week's memories into a factlist/meta-summary (by invoking AI)
* Create new post in new conversation (if missive)
* Create new thread in private channel (if Discord)

**Comment by rajivsinclair** [comment]
For context and draft prompt, see [doc](https://docs.pdw.co/tachio-overview)

**Comment by ejfox** [comment]
Stale
